apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-nginx
  name: frontend-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-nginx
  template:
    metadata:
      labels:
        app: frontend-nginx
    spec:
      containers:
      - image: 595362810845.dkr.ecr.ap-northeast-2.amazonaws.com/k8s-cluster-repo:v3.0
        name: frontend-nginx


















